import { execFileSync } from "node:child_process";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
const json = JSON.parse(
  execFileSync(
    "npx",
    ["playwright", "test", "-c", "playwright.automation.config.ts", "--list", "--reporter=json"],
    { encoding: "utf8", maxBuffer: 20 * 1024 * 1024 },
  ),
);
const rows = [];
function walk(s, file = s.file) {
  for (const spec of s.specs ?? [])
    rows.push({ title: spec.title, file: `tests/${file ?? spec.file}` });
  for (const child of s.suites ?? []) walk(child, file ?? child.file);
}
for (const s of json.suites) walk(s);
const feature = readFileSync("tests/automation/bdd/appearance.feature", "utf8");
const bdd = [...feature.matchAll(/^\s*\| (\d{3}) \| (\w+) \| (\w+) \|/gm)].map((m) => ({
  id: `DC-BDD-${m[1]}`,
  title: `${m[2]} display with ${m[3]} workspace`,
  file: "tests/automation/bdd/appearance.feature",
}));
if (rows.length !== 352 || bdd.length !== 48)
  throw Error(`Expected 352 Playwright + 48 Cucumber; got ${rows.length} + ${bdd.length}`);
let n = 0;
for (const row of rows)
  row.id = row.title.match(/^DC-[A-Z0-9-]+-\d+/)?.[0] ?? `DC-REG-${String(++n).padStart(3, "0")}`;
const all = [...rows, ...bdd];
if (new Set(all.map((r) => r.id)).size !== 400) throw Error("Duplicate scenario IDs");
mkdirSync("docs/automation", { recursive: true });
writeFileSync(
  "docs/automation/scenario-inventory.json",
  JSON.stringify(
    { functional: 400, playwright: 352, cucumber: 48, performance: 20, unit: 55, scenarios: all },
    null,
    2,
  ),
);
const counts = {};
for (const r of all) {
  const key = r.id.replace(/-\d+$/, "");
  counts[key] = (counts[key] ?? 0) + 1;
}
writeFileSync(
  "docs/automation/SCENARIOS.md",
  `# DocuCore automation inventory\n\n400 functional scenarios: 352 Playwright/API + 48 Cucumber. The 20 k6 workloads and existing 55 unit/database tests are separate counts.\n\n| Group | Cases |\n|---|---:|\n${Object.entries(
    counts,
  )
    .map(([k, v]) => `| ${k} | ${v} |`)
    .join(
      "\n",
    )}\n\nGenerated by \`npm run automation:inventory\`; [machine-readable inventory](scenario-inventory.json) lists every ID and source file.\n`,
);
console.log(
  "Inventory verified: 352 Playwright + 48 Cucumber = 400 functional; 20 k6 workloads tracked separately.",
);
