import Link from "next/link";
export const metadata = { title: "Help & resources" };
export default function Page() {
  return (
    <>
      <div className="page-intro">
        <div>
          <h1>Help & resources</h1>
          <p>Guides, supported formats and answers for your document workspace.</p>
        </div>
      </div>
      <div className="panel prose max-w-3xl">
        <h2>What can I use today?</h2>
        <p>
          Read, search and print PDFs. Merge documents, split by ranges, reorder and rotate pages,
          duplicate or delete pages, insert blank pages, convert images to PDF, and export PDF pages
          as JPG, PNG or WebP. OCR, image editing, basic Office conversion, PDF forms, redaction and
          AES-256 protection also run on your device.
        </p>
        <h2>Supported formats and limits</h2>
        <p>
          PDF, JPG/JPEG, PNG, WebP, DOCX, XLSX, plain text, CSV and HTML are supported by their
          respective tools. Each input may be up to 25 MB, with at most 20 inputs and 100 MB
          combined. Core PDF tools support up to 500 pages; raster and OCR workflows support up to
          100 pages. Browser memory may impose lower practical limits. For large jobs, select fewer
          pages or use a lower image resolution.
        </p>
        <div className="faq">
          <details>
            <summary>Will my original file change?</summary>
            <p>
              No. Tools generate a separate output document. The original file remains unchanged on
              your device.
            </p>
          </details>
          <details>
            <summary>Can I open a password-protected PDF?</summary>
            <p>
              The reader supports a valid document password. Use Unlock PDF with the correct
              password before structural editing or conversion. Password cracking is not supported.
            </p>
          </details>
          <details>
            <summary>What happens to forms, bookmarks and signatures?</summary>
            <p>
              Page copying is designed for page content. Document-level outlines, interactive form
              behavior, attachments and cryptographic signatures may not survive a merge or split.
              Inspect the output before using it for important workflows.
            </p>
          </details>
          <details>
            <summary>Can I edit existing text or run OCR?</summary>
            <p>
              The PDF editor supports visual text replacement overlays. Multilingual OCR creates
              editable text and searchable PDFs. The separate Redact PDF tool rebuilds page images
              and discards underlying text. Exact native PDF text editing is not supported.
            </p>
          </details>
          <details>
            <summary>Why did conversion not make my file smaller?</summary>
            <p>
              Conversion changes a format; it does not guarantee compression. Structural PDF
              optimization keeps the original if it cannot reduce size. Lossy raster compression
              removes text and forms. Output file size is calculated from the real generated bytes.
            </p>
          </details>
          <details>
            <summary>Why did I not receive a reset email?</summary>
            <p>
              Account email requires an administrator to configure SMTP. If it is configured, check
              your spam folder and ask the administrator to verify delivery. Reset links expire and
              can be used only once.
            </p>
          </details>
        </div>
        <h2>Personalize your workspace</h2>
        <p>
          Open{" "}
          <Link className="underline" href="/settings">
            Workspace settings
          </Link>{" "}
          to choose from eight workspace colour themes, then pick light, dark or system display
          mode. High contrast and colourful headers are optional. Save appearance to sync your
          choice to your account.
        </p>
        <p>
          For password changes, open{" "}
          <Link className="underline" href="/profile/settings">
            Account security
          </Link>
          . For storage and data handling, read{" "}
          <Link className="underline" href="/privacy">
            Our privacy approach
          </Link>
          .
        </p>
        <h2>Need a starting point?</h2>
        <p>
          <Link className="text-[var(--primary)] underline" href="/tools">
            Explore all available tools
          </Link>{" "}
          or open a PDF directly from the overview.
        </p>
      </div>
    </>
  );
}
